# Generated by Django 3.1.14 on 2022-12-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('povt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_text',
            field=models.CharField(max_length=200),
        ),
    ]
